
on:
    push:
        paths-ignore:
            - "ops/**"
            - "**.md"
            - "docs/**"
            - "CODEOWNERS"
        branches-ignore:
          - 'refs/tags/*'
    release:
        types:
          - published
jobs:
    build1:
        runs-on: ubuntu-latest
        steps:
          - run: echo "Hello"
    build2:
      if: ${{ vars.ABC }} == 'hello'
      runs-on: ubuntu-latest
      steps:
        - run: echo "Hello"
    build13:
      needs: [build1, build2]
      runs-on: ubuntu-latest
      steps:
        - run: echo "Hello"