
on:
  push
  
jobs:
    build1:
        runs-on: ubuntu-latest
        steps:
          - run: echo "Hello" && exit 1
    build2:
      if: github.ref_name == 'hello'
      runs-on: ubuntu-latest
      steps:
        - run: echo "Hello"
    build13:
      needs: [build1, build2]
      if: always()
      runs-on: ubuntu-latest
      steps:
        - run: echo "Hello"